//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCsharpASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta
    {
        public int Id_Consulta { get; set; }
        public int Doctor_Id { get; set; }
        public int Paciente_Id { get; set; }
        public Nullable<System.DateTime> FechaConsulta { get; set; }
        public string Diagnostico { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
